development:
  host: localhost
  username: ahmad
  password:
  database: dawa_asan
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432


production:
  host: localhost
  username: ahmad
  password:
  database: dawa_asan
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432